name: Update GitHub Stats

on:
  schedule:
    - cron: '0 0 * * *'  
  workflow_dispatch:  
  push:
    branches: [ main ]

jobs:
  update-stats:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: |
        npm init -y
        npm install @octokit/rest
        npm init -y
        npm install @octokit/rest
        echo '{"type": "module"}' > package.json
        
    - name: Update README with stats
      run: node update-stats.js
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Commit changes
      run: |
        git config --local user.email "abbilginn@hotmail.com"
        git config --local user.name "GitHub Action"
        git add README.md
        git diff --staged --quiet || git commit -m "Update GitHub stats"
        git push
